# frozen_string_literal: true

source "https://rubygems.org"

group :test do
    gem 'capybara', '3.33'
    gem 'cucumber', '3.1.2'
    gem 'rspec', '3.7.0'
    gem 'selenium-webdriver', '3.141'
  end
